### ISSUE TITLE
デモサイトで動画を追加しようとしたらContent missingになる

### ISSUE THREAD

**Issue by miminashi** [miminashi/ytdlor#69]
<img width="1607" alt="スクリーンショット 2024-08-11 12 14 48" src="https://github.com/user-attachments/assets/e7099b8c-97c9-4a92-9c90-0f4e5336aabf">

ログ
```
web-1          | I, [2024-08-11T03:17:02.477469 #1]  INFO -- : [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3] Started POST "/archives" for 126.88.113.129 at 2024-08-11 03:17:02 +0000
web-1          | I, [2024-08-11T03:17:02.479003 #1]  INFO -- : [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3] Processing by ArchivesController#create as TURBO_STREAM
web-1          | I, [2024-08-11T03:17:02.479112 #1]  INFO -- : [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3]   Parameters: {"authenticity_token"=>"[FILTERED]", "archive"=>{"original_url"=>"https://www.youtube.com/watch?v=7ZZN1wlmULU"}, "commit"=>"動画を追加"}
web-1          | E, [2024-08-11T03:17:02.486471 #1] ERROR -- : [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3] [ActiveJob] Failed enqueuing ThumbnailDownloadJob to SolidQueue(thumbnail): ActiveJob::SerializationError (Unable to serialize Archive without an id. (Maybe you forgot to call save?))
web-1          | I, [2024-08-11T03:17:02.486832 #1]  INFO -- : [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3] Completed 500 Internal Server Error in 7ms (ActiveRecord: 2.9ms | Allocations: 922)
web-1          | F, [2024-08-11T03:17:02.488856 #1] FATAL -- : [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3]   
web-1          | [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3] ActiveJob::SerializationError (Unable to serialize Archive without an id. (Maybe you forgot to call save?)):
web-1          | [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3]   
web-1          | [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3] app/models/archive.rb:65:in `update_thumbnail_later'
web-1          | [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3] app/models/archive.rb:205:in `after_create_commit'
web-1          | [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3] app/controllers/archives_controller.rb:28:in `block in create'
web-1          | [d8e449f7-a0b9-4eba-9d95-1aa2ca4105e3] app/controllers/archives_controller.rb:27:in `create'
```

**Comment by miminashi** [comment]
#70 をやったら以下のようになった

```
web-1          | I, [2024-08-11T03:50:19.752372 #1]  INFO -- : [6a0a982e-3763-4a70-9abc-a763f3441ec2] Started POST "/archives" for 126.88.113.129 at 2024-08-11 03:50:19 +0000
web-1          | I, [2024-08-11T03:50:19.753606 #1]  INFO -- : [6a0a982e-3763-4a70-9abc-a763f3441ec2] Processing by ArchivesController#create as TURBO_STREAM
web-1          | I, [2024-08-11T03:50:19.753686 #1]  INFO -- : [6a0a982e-3763-4a70-9abc-a763f3441ec2]   Parameters: {"authenticity_token"=>"[FILTERED]", "archive"=>{"original_url"=>"https://youtube.com/shorts/0jtGdwRbInE?si=yC5l3pJDw98pI7oW"}, "commit"=>"動画を追加"}
web-1          | I, [2024-08-11T03:50:19.777152 #1]  INFO -- : [6a0a982e-3763-4a70-9abc-a763f3441ec2] [ActiveJob] Enqueued ThumbnailDownloadJob (Job ID: 4f208b2b-398c-4879-9faa-a1eed1a60dbb) to SolidQueue(thumbnail)
web-1          | I, [2024-08-11T03:50:19.782941 #1]  INFO -- : [6a0a982e-3763-4a70-9abc-a763f3441ec2] [ActiveJob] Enqueued VideosDownloadJob (Job ID: 43586cc7-3f5f-4898-b29f-a49c8f212e92) to SolidQueue(video)
web-1          | E, [2024-08-11T03:50:19.784402 #1] ERROR -- : [6a0a982e-3763-4a70-9abc-a763f3441ec2] [ActiveJob] Failed enqueuing Turbo::Streams::ActionBroadcastJob to SolidQueue(default): ActiveJob::SerializationError (Unable to serialize Archive without an id. (Maybe you forgot to call save?))
web-1          | I, [2024-08-11T03:50:19.784676 #1]  INFO -- : [6a0a982e-3763-4a70-9abc-a763f3441ec2] Completed 500 Internal Server Error in 31ms (ActiveRecord: 14.5ms | Allocations: 3157)
web-1          | F, [2024-08-11T03:50:19.787026 #1] FATAL -- : [6a0a982e-3763-4a70-9abc-a763f3441ec2]   
web-1          | [6a0a982e-3763-4a70-9abc-a763f3441ec2] ActiveJob::SerializationError (Unable to serialize Archive without an id. (Maybe you forgot to call save?)):
web-1          | [6a0a982e-3763-4a70-9abc-a763f3441ec2]   
web-1          | [6a0a982e-3763-4a70-9abc-a763f3441ec2] app/controllers/archives_controller.rb:28:in `block in create'
web-1          | [6a0a982e-3763-4a70-9abc-a763f3441ec2] app/controllers/archives_controller.rb:27:in `create'
```

**Comment by miminashi** [comment]
#73 で解決済み
